config/routes.rb
Contacts::Application.routes.draw do
  get "home/index"

  get "home/callback"

  get "auth/facebook"

  get "auth/close"

  get "auth/sign_out"

  get "auth/callback"

  get "search/index"
  match 'search' => 'search#index'
  get "results/index"
  match 'results' => 'results#index'
  resources :services

  resources :districts

  resources :countries

  resources :contacts
  root :to => 'search#index'

end

app/models/service.rb
class Service < ActiveRecord::Base
  attr_accessible :name
  
  	def self.all_to_array
		array = Service.all
		str = ""
		array.each { |e|
			str += '"'+e.name+'"'
			if e != array.last
				str += ","
			end
		}
		return str
	end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  # GET /services
  # GET /services.json
  def index
    @services = Service.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @services }
    end
  end

  # GET /services/1
  # GET /services/1.json
  def show
    @service = Service.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/new
  # GET /services/new.json
  def new
    @service = Service.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @service }
    end
  end

  # GET /services/1/edit
  def edit
    @service = Service.find(params[:id])
  end

  # POST /services
  # POST /services.json
  def create
    @service = Service.new(params[:service])

    respond_to do |format|
      if @service.save
        format.html { redirect_to '/services', notice: 'Service was successfully created.' }
        format.json { render json: @service, status: :created, location: @service }
      else
        format.html { render action: "new" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /services/1
  # PUT /services/1.json
  def update
    @service = Service.find(params[:id])

    respond_to do |format|
      if @service.update_attributes(params[:service])
        format.html { redirect_to '/services', notice: 'Service was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service = Service.find(params[:id])
    @service.destroy

    respond_to do |format|
      format.html { redirect_to services_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<div class="row">
  <!-- Example form styling -->
  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2><%= "Thêm" if @service == nil%> Dịch Vụ</h2>
        <%if @service != nil %>
        <ul class="data-header-actions">
          <li>
            <a href="<%= services_path %>" class="btn btn-success">Dịch Vụ</a>
          </li>
        </ul>
        <% end %>
      </header>
      <section>
        <% @service = Service.new if @service == nil%>
        <%= form_for(@service,:html=>
        {:class=>"form-inline"}) do |f| %>
        <fieldset>
          <div class="control-group">
            <label class="control-label">Quận</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :name %></div>
            </div>
          </div>
          <div class="form-actions">
            <%= f.submit 'Save',:class=>'btn btn-alt btn-primary btn-large' %></div>
        </fieldset>
        <% end %></section>
    </div>
  </article>
  <!-- /Data block -->
</div>
<script type="text/javascript">
  <% if notice != nil %>
    alert('<%= notice%>');
  <% end %>
</script>

app/views/services/edit.html.erb
<%= render 'form' %>

app/views/services/index.html.erb
<!-- Grid row -->
<div class="row">

    <!-- Example jQuery FullCalendar -->
    <!-- Data block -->
    <article class="span6 data-block">
        <div class="data-container">
            <header>
                <h2>Dịch Vụ</h2>
            </header>
            <section class="tab-content">
                <!-- Tab #static -->
                <div class="tab-pane active" id="static">
                    <table class="table table-condensed">
                        <thead>
                            <tr>

                                <th>Dịch Vụ</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @services.each do |service| %>
                            <tr>
                                <td>
                                    <span class="label btn-info">
                                        <%= service.name %></span>
                                </td>
                                <td>
                                    <%= link_to 'Show', service,:class=>
                                    "label label-success" %>
                                    <%= link_to 'Edit', edit_service_path(service),:class=>
                                    "label label-success" %>
                                    <%= link_to 'Destroy', service, method: :delete, data: { confirm: "Thực sự muốn xóa #{service.name} ?" },:class=>"label label-important" %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /Tab #dynamic --> </section>
        </div>
    </article>
    <!-- /Data block -->
    <%= render :partial =>"services/form"  %></div>
</div>
<!-- /Grid row -->

app/views/services/new.html.erb
<h1>New service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @service.name %>
</p>


<%= link_to 'Edit', edit_service_path(@service) %> |
<%= link_to 'Back', services_path %>