config/routes.rb
Contacts::Application.routes.draw do
  get "home/index"

  get "home/callback"

  get "auth/facebook"

  get "auth/close"

  get "auth/sign_out"

  get "auth/callback"

  get "search/index"
  match 'search' => 'search#index'
  get "results/index"
  match 'results' => 'results#index'
  resources :services

  resources :districts

  resources :countries

  resources :contacts
  root :to => 'search#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
	attr_accessible :address, :city, :country, :description, :service, :district, :img_default, :name, :province,:ward,:longitude_late,:latitude_late

	acts_as_gmappable


	def gmaps4rails_address
		address
	end
	def gmaps4rails_infowindow
		info = '/contacts/' + id.to_s
		book = 'B&#7841;n &#273;&#227; &#273;&#7863;t ch&#7895; th&#224;nh c&#244;ng [ ',name,' ]'
		"<span class='label btn-info btn-small'>#{name}</span> <a href='#{info}' class='label btn-success btn-small'>Xem</a> <a href='javascript:alert(#{book});' class='label btn-danger'>&#272;&#7863;t Ch&#7895;</a><br/>#{address} / #{province} / #{district}"
	end
	def gmaps4rails_sidebar
		"<span class='label btn-info btn-mini'>#{name}<span>"
	end

	before_save :fixed_address
	before_update :fixed_address

	after_save :fixed_address
	after_update :fixed_address
	private
	def fixed_address
		self.gmaps = true
		self.latitude = self.latitude_late
		self.longitude = self.longitude_late
	end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contacts }
    end
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
    @contact = Contact.find(params[:id])

    @json = @contact.to_gmaps4rails
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/new
  # GET /contacts/new.json
  def new
    @contact = Contact.new

    @json = District.all.to_gmaps4rails
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contact }
    end
  end

  # GET /contacts/1/edit
  def edit
    @contact = Contact.find(params[:id])
    @json = @contact.to_gmaps4rails
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(params[:contact])
    @contact.gmaps = true
    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render json: @contact, status: :created, location: @contact }
      else
        format.html { render action: "new" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contacts/1
  # PUT /contacts/1.json
  def update
    @contact = Contact.find(params[:id])
    @contact.gmaps = true
    respond_to do |format|
      if @contact.update_attributes(params[:contact])
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact = Contact.find(params[:id])
    @contact.destroy

    respond_to do |format|
      format.html { redirect_to contacts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_form.html.erb
<div class="row">
  <!-- Example form styling -->
  <!-- Data block -->
  <article class="span12 data-block">
    <div class="data-container">
      <header>
        <h2>
          <%= (@contact.name == nil)? "Thêm Danh Bạ": @contact.name %></h2>
        <ul class="data-header-actions">
          <li>
            <a href="<%= contacts_path %>" class="btn btn-success">Danh Bạ</a>
          </li>
        </ul>
      </header>
      <section>
        <%= form_for(@contact,:html =>
        { :class => "form-inline" }) do |f| %>
        <fieldset>
          <div class="control-group">
            <label class="control-label">Tên</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :name %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Dịch Vụ</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= select_tag "contact[service]", options_from_collection_for_select(Service.all, "name", "name",@contact.service), :include_blank =>true %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Địa Chỉ</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :address %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Quốc Gia</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :country %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Tỉnh</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :ward %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Thành Phố</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :city %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Quận</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= select_tag "contact[district]", options_from_collection_for_select(District.all, "name", "name",@contact.district), :include_blank =>true %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Phường</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :province %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Hình Đại Diện</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :img_default %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Thông Tin</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_area :description,:class=>"span5",:style=>"height:200px" %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Kinh Độ</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :longitude_late %></div>
            </div>
          </div>
          <div class="control-group">
            <label class="control-label">Vĩ Độ</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :latitude_late %></div>
            </div>
          </div>
          <div class="form-actions">
            <%= f.submit 'Save',:class=>'btn btn-alt btn-primary btn-large' %></div>
        </fieldset>
        <% end %></section>
    </div>
  </article>
  <!-- /Data block -->
</div>
<!-- /Grid row -->

<div class="row">

  <!-- Example jQuery FullCalendar -->
  <!-- Data block -->
  <article class="span12 data-block">
    <div class="data-container">
      <section class="tab-content">
        <!-- detect_location" =>
        true, -->
        <ul id="markers_list"></ul>
        <%= gmaps("markers" =>
        {"data" => @json,"options" => {"list_container" => "markers_list","draggable" => true  }},"map_options" => {"processing" => "json","auto_adjust" => true, "auto_zoom" => false, "zoom" => 16}) %>
      </section>
    </div>
  </article>
  <!-- /Data block -->
</div>

<% content_for :scripts do %>
<script type="text/javascript" charset="utf-8">

Gmaps.map.HandleDragend = function(pos) {
  var geocoder = new google.maps.Geocoder();
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      console.log(responses[0].geometry.location.$a);
      console.log(responses[0].geometry.location.ab);
      $('#contact_latitude_late').val(responses[0].geometry.location.$a);
      $('#contact_longitude_late').val(responses[0].geometry.location.ab)
    } else {
    alert('Cannot determine address at this location.');
    }
  });
};

Gmaps.map.callback = function() {
  for (var i = 0; i <  this.markers.length; ++i) {
     google.maps.event.addListener(Gmaps.map.markers[i].serviceObject, 'dragend', function() { Gmaps.map.HandleDragend(this.getPosition()) });
  }
};

// Google map loaded
// $(document).ready(function(){
//   Gmaps.map.callback = function(){
//     for (index = _i = 0, _len = this.markers.length; _i < _len; index = ++_i) {
//       marker = this.markers[index];
//       if (!(this.markers[index].serviceObject == null)) {
//         Lat = this.markers[index].lat;
//         Lng = this.markers[index].lng;
//         if (this.markers_conf.randomize) {
//           LatLng = this.randomize(Lat, Lng);
//           Lat = LatLng[0];
//           Lng = LatLng[1];
//         }
//         this.markers[index].serviceObject = this.createMarker({
//           "marker_picture": this.markers[index].picture ? this.markers[index].picture : this.markers_conf.picture,
//           "marker_width": this.markers[index].width ? this.markers[index].width : this.markers_conf.width,
//           "marker_height": this.markers[index].height ? this.markers[index].height : this.markers_conf.length,
//           "marker_title": this.markers[index].title ? this.markers[index].title : null,
//           "marker_anchor": this.markers[index].marker_anchor ? this.markers[index].marker_anchor : null,
//           "shadow_anchor": this.markers[index].shadow_anchor ? this.markers[index].shadow_anchor : null,
//           "shadow_picture": this.markers[index].shadow_picture ? this.markers[index].shadow_picture : null,
//           "shadow_width": this.markers[index].shadow_width ? this.markers[index].shadow_width : null,
//           "shadow_height": this.markers[index].shadow_height ? this.markers[index].shadow_height : null,
//           "marker_draggable": this.markers[index].draggable ? this.markers[index].draggable : this.markers_conf.draggable,
//           "rich_marker": this.markers[index].rich_marker ? this.markers[index].rich_marker : null,
//           "zindex": this.markers[index].zindex ? this.markers[index].zindex : null,
//           "Lat": Lat,
//           "Lng": Lng,
//           "index": index
//         });
//         Gmaps.map.createSidebarCustom(this.markers[index]);
//       }
//     }
//     this.markers_conf.offset = this.markers.length
//   };
// });

//moves map to marker clicked + open infowindow
  // sidebar_element_handler : (currentMap, marker, eventType) ->
  //   return () ->
  //     currentMap.map.panTo(marker.position)
  //     google.maps.event.trigger(marker, eventType)
// end Google map loaded
</script>

<style type="text/css">
#markers_list{
  list-style-type:none;
  display: inline-block;
  #mark
}
#markers_list li{
  float:left;
  margin-left:5px;
}
</style>

<style type="text/css">
.map_container {
  padding: 6px;
  border-width: 1px;
  border-style: solid;
  border-color: #ccc #ccc #999 #ccc;
  -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
  width: 630px;
}

.gmaps4rails_map {
  width: 630px;
  height: 400px;
}

.bing_map {
   position: absolute;
   top: 20;
   left: 10;
   width: 630px;
   height: 400px;
   border:#555555 2px solid;
}
#map img { 
  max-width: none;
}
#map label { 
  width: auto; display:inline; 
}
</style>
<% end %>

app/views/contacts/edit.html.erb
<%= render 'form' %>

app/views/contacts/index.html.erb
<!-- Grid row -->
<div class="row">

    <!-- Example jQuery FullCalendar -->
    <!-- Data block -->
    <article class="span12 data-block">
        <div class="data-container">
            <header>
                <h2>Địa Chỉ</h2>
                <ul class="data-header-actions">
                    <li class="demoTabs active">
                        <a href="<%= new_contact_path%>" class="btn btn-alt btn-inverse">Thêm Địa Chỉ</a>
                    </li>
                </ul>
            </header>
            <section class="tab-content">
                <!-- Tab #static -->
                <div class="tab-pane active" id="static">
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                                <th></th>
                                <th>Tên</th>
                                <th>Dịch Vụ</th>
                                <th>Quận</th>
                                <th>Địa Chỉ</th>
                                <th></th>
                                <th></th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @contacts.each do |contact| %>
                            <tr>
                                <td>
                                    <a href"#" class="thumbnail" style="width:48px;height:48px">
                                        <img src="<%= contact.img_default %>"></a>
                                </td>
                                <td> <b><%= contact.name %> <b></td>
                                <td>
                                    <span class="label btn-success">
                                        <%= contact.service %></span>
                                </td>

                                 <td>
                                    <span class="label btn-info">
                                        <%= contact.district %></span>
                                </td>
                                <td>
                                    <span class="label label-warning">
                                        <%= contact.address %></span>
                                </td>
                                <td>
                                    <%= link_to 'Show', contact,:class=>
                                    "label label-success" %>
                                    <%= link_to 'Edit', edit_contact_path(contact),:class=>
                                    "label label-success" %>
                                    <%= link_to 'Destroy', contact, method: :delete, data: { confirm: "Thực sự muốn xóa #{contact.name} ?" },:class=>"label label-important" %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /Tab #dynamic --> </section>
        </div>
    </article>
    <!-- /Data block --> 
</div>
<!-- /Grid row -->

app/views/contacts/new.html.erb
<%= render 'form' %>

app/views/contacts/show.html.erb
<div class="row">
  <!-- Example form styling -->
  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2><%= @contact.name %></h2>
        <ul class="data-header-actions">
          <li>
            <a href="<%= edit_contact_path(@contact) %>" class="btn btn-danger">Chỉnh Sửa</a>
          </li>
          <li>
            <a href="<%= contacts_path %>" class="btn btn-success">Danh Bạ</a>
          </li>
        </ul>
      </header>
      <section>
        <form class="form-inline">
          <fieldset>
            <div class="control-group">
              <label class="control-label">Tên</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.name %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Địa Chỉ</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.address %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Quốc Gia</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.country %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Tỉnh</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.ward %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Thành Phố</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.city %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Quận</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.district %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Phường</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <span class="add-on">
                    <%= @contact.province %></span>
                </div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Hình Đại Diện</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <a href"<%= @contact.img_default %>
                    "="" class="thumbnail" style="width:48px;height:48px">
                    <img src="/assets/thumb/48x48.png"></a>
                </div>
              </div>
            </div>
          </fieldset>
        </form>
      </section>
    </div>
  </article>
  <!-- /Data block -->

  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2>Thông Tin </h2>
      </header>
      <section>
        <p>
          <%= raw @contact.description %></p>

        <ul id="markers_list"></ul>
        <%= gmaps("markers" =>
        {"data" => @json,"options" => {"list_container" => "markers_list"}},"map_options" => {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 16}) %></section>
    </div>
  </article>
  <!-- /Data block -->
</div>


<!-- /Grid row -->
<% content_for :scripts do %>
<style type="text/css">
.map_container {
  padding: 6px;
  border-width: 1px;
  border-style: solid;
  border-color: #ccc #ccc #999 #ccc;
  -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
  width: 280px;
}

.gmaps4rails_map {
  width: 280px;
  height: 390px;
}

.bing_map {
   position: absolute;
   top: 20;
   left: 10;
   width: 280px;
   height: 390px;
   border:#555555 2px solid;
}
#map img { 
  max-width: none;
}
#map label { 
  width: auto; display:inline; 
} 

#markers_list{
  list-style-type:none;
  display: inline-block;
  #mark
}
#markers_list li{
  float:left;
  margin-left:5px;
}
#markers_list li a{
  text-decoration: none;
}
</style>
<% end %>