config/routes.rb
Contacts::Application.routes.draw do
  get "home/index"

  get "home/callback"

  get "auth/facebook"

  get "auth/close"

  get "auth/sign_out"

  get "auth/callback"

  get "search/index"
  match 'search' => 'search#index'
  get "results/index"
  match 'results' => 'results#index'
  resources :services

  resources :districts

  resources :countries

  resources :contacts
  root :to => 'search#index'

end

app/models/district.rb
class District < ActiveRecord::Base
	attr_accessible :name,:longitude_late,:latitude_late,:latitude,:longitude

	acts_as_gmappable


	def gmaps4rails_address
		address
	end
	def gmaps4rails_infowindow
		"#{self.name}"
	end
	def gmaps4rails_sidebar
		"<span class='label btn-info'>#{name}</span>"
	end

	def self.all_to_array
		array = District.all
		str = ""
		array.each { |e|
			str += '"'+e.name+'"'
			if e != array.last
				str += ","
			end
		}
		return str
	end

	
	before_save :fixed_address
	before_update :fixed_address
	after_save :fixed_address
	after_update :fixed_address
	private
	def fixed_address
		self.gmaps = true
		self.latitude = self.latitude_late
		self.longitude = self.longitude_late
	end
end

app/controllers/districts_controller.rb
class DistrictsController < ApplicationController
  # GET /districts
  # GET /districts.json
  def index
    @districts = District.all
    @json = District.all.to_gmaps4rails
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @districts }
    end
  end

  # GET /districts/1
  # GET /districts/1.json
  def show
    @district = District.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @district }
    end
  end

  # GET /districts/new
  # GET /districts/new.json
  def new
    @district = District.new
    @json = Location.all.to_gmaps4rails
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @district }
    end
  end

  # GET /districts/1/edit
  def edit
    @json = District.find(params[:id]).to_gmaps4rails
    @district = District.find(params[:id])
  end

  # POST /districts
  # POST /districts.json
  def create
    @district = District.new(params[:district])
    @district.gmaps = true
    respond_to do |format|
      if @district.save
        format.html { redirect_to @district, notice: 'District was successfully created.' }
        format.json { render json: @district, status: :created, location: @district }
      else
        format.html { render action: "new" }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /districts/1
  # PUT /districts/1.json
  def update
    @district = District.find(params[:id])
    @district.gmaps = true
    respond_to do |format|
      if @district.update_attributes(params[:district])
        format.html { redirect_to @district, notice: 'District was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @district.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /districts/1
  # DELETE /districts/1.json
  def destroy
    @district = District.find(params[:id])
    @district.destroy

    respond_to do |format|
      format.html { redirect_to districts_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/districts_helper.rb
module DistrictsHelper
end

app/views/districts/_form.html.erb
<div class="row">
  <!-- Example form styling -->
  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2>Thêm Quận - Huyện</h2>
        <ul class="data-header-actions">
          <li>
            <a href="<%= districts_path %>" class="btn btn-success">Quận - Huyện</a>
          </li>
        </ul>
      </header>
      <section>
        <%= form_for(@district,:html=>{:class=>"form-inline"}) do |f| %>
          <fieldset>
            <div class="control-group">
              <label class="control-label">Quận</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <%= f.text_field :name %></div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Kinh Độ</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <%= f.text_field :longitude_late %></div>
              </div>
            </div>
            <div class="control-group">
              <label class="control-label">Vĩ Độ</label>
              <div class="form-controls">
                <div class="input-prepend">
                  <%= f.text_field :latitude_late %></div>
              </div>
            </div>
            <div class="form-actions">
              <%= f.submit 'Save',:class=>'btn btn-alt btn-primary btn-large' %></div>
          </fieldset>
        <% end %>
      </section>
    </div>
  </article>
  <!-- /Data block -->

  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2>Bản Đồ</h2>
      </header>
      <section>
        <%= gmaps("markers" =>
        {"data" => @json,"options" => { "draggable" => true  }}, "map_options" => {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 12}) %>
      </section>
    </div>
  </article>
  <!-- /Data block -->
</div>

<% content_for :scripts do %>
<script type="text/javascript" charset="utf-8">

Gmaps.map.HandleDragend = function(pos) {
  var geocoder = new google.maps.Geocoder();
  geocoder.geocode({
    latLng: pos
  }, function(responses) {
    if (responses && responses.length > 0) {
      $('#district_latitude_late').val(responses[0].geometry.location.$a);
      $('#district_longitude_late').val(responses[0].geometry.location.ab)
      console.log(responses[0].geometry.location.$a);
      console.log(responses[0].geometry.location.ab);
    } else {
    alert('Cannot determine address at this location.');
    }
  });
};

Gmaps.map.callback = function() {
  for (var i = 0; i <  this.markers.length; ++i) {
     google.maps.event.addListener(Gmaps.map.markers[i].serviceObject, 'dragend', function() { Gmaps.map.HandleDragend(this.getPosition()) });
  }
};
</script>

<style type="text/css">
.map_container {
  padding: 6px;
  border-width: 1px;
  border-style: solid;
  border-color: #ccc #ccc #999 #ccc;
  -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
  width: 280px;
}

.gmaps4rails_map {
  width: 280px;
  height: 400px;
}

.bing_map {
   position: absolute;
   top: 20;
   left: 10;
   width: 280px;
   height: 400px;
   border:#555555 2px solid;
}
#map img { 
  max-width: none;
}
#map label { 
  width: auto; display:inline; 
} 
</style>
<% end %>

app/views/districts/edit.html.erb
<%= render 'form' %>

app/views/districts/index.html.erb
<!-- Grid row -->
<div class="row">

    <!-- Example jQuery FullCalendar -->
    <!-- Data block -->
    <article class="span12 data-block">
        <div class="data-container">
            <header>
                <h2>Quận - Huyện</h2>
                <ul class="data-header-actions">
                    <li class="demoTabs active">
                        <a href="<%= new_district_path %>" class="btn btn-alt btn-inverse">Thêm Quận - Huyện</a>
                    </li>
                </ul>
            </header>
            <section class="tab-content">
                <!-- Tab #static -->
                <div class="tab-pane active" id="static">
                    <table class="table table-condensed">
                        <thead>
                            <tr>

                                <th>Quận</th>
                                <th>Kinh Độ x Vĩ Độ</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <% @districts.each do |district| %>
                            <tr>
                                <td>
                                    <span class="label btn-info">
                                        <%= district.name %></span>
                                </td>

                                <td>
                                    <span class="label btn-warning">
                                        <%= district.longitude %></span><span class="label label-important">
                                        <%= district.latitude %></span>
                                </td>
                                <td>
                                    <%= link_to 'Show', district,:class=>
                                    "label label-success" %>
                                    <%= link_to 'Edit', edit_district_path(district),:class=>
                                    "label label-success" %>
                                    <%= link_to 'Destroy', district, method: :delete, data: { confirm: "Thực sự muốn xóa #{district.name} ?" },:class=>"label label-important" %></td>
                            </tr>
                            <% end %>
                        </tbody>
                    </table>
                </div>
                <!-- /Tab #dynamic --> </section>
        </div>
    </article>
    <!-- /Data block -->
</div>
<!-- /Grid row -->
<!-- Grid row -->
<div class="row">

    <!-- Example jQuery FullCalendar -->
    <!-- Data block -->
    <article class="span12 data-block">
        <div class="data-container">
            <section class="tab-content">
                <%= gmaps("markers" => {"data" => @json,"options" => {}}, "map_options" => {"processing" => "json", "auto_adjust" => true, "auto_zoom" => false, "zoom" => 12}) %>
            </section>
        </div>
    </article>
    <!-- /Data block -->
</div>
<!-- /Grid row -->
<% content_for :scripts do %>
<style type="text/css">
.map_container {
  padding: 6px;
  border-width: 1px;
  border-style: solid;
  border-color: #ccc #ccc #999 #ccc;
  -webkit-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  -moz-box-shadow: rgba(64, 64, 64, 0.5) 0 2px 5px;
  box-shadow: rgba(64, 64, 64, 0.1) 0 2px 5px;
  width: 630px;
}

.gmaps4rails_map {
  width: 630px;
  height: 400px;
}

.bing_map {
   position: absolute;
   top: 20;
   left: 10;
   width: 630px;
   height: 400px;
   border:#555555 2px solid;
}
#map img { 
  max-width: none;
}
#map label { 
  width: auto; display:inline; 
} 

#markers_list{
  list-style-type:none;
  display: inline-block;
  #mark
}
#markers_list li{
  float:left;
  margin-left:5px;
}
</style>
<% end %>

app/views/districts/new.html.erb
<%= render 'form' %>r

app/views/districts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @district.name %>
</p>


<%= link_to 'Edit', edit_district_path(@district) %> |
<%= link_to 'Back', districts_path %>