config/routes.rb
Contacts::Application.routes.draw do
  get "home/index"

  get "home/callback"

  get "auth/facebook"

  get "auth/close"

  get "auth/sign_out"

  get "auth/callback"

  get "search/index"
  match 'search' => 'search#index'
  get "results/index"
  match 'results' => 'results#index'
  resources :services

  resources :districts

  resources :countries

  resources :contacts
  root :to => 'search#index'

end

app/models/country.rb
class Country < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @countries }
    end
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
    @country = Country.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/new
  # GET /countries/new.json
  def new
    @country = Country.new
    render :action => :index
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @country }
    end
  end

  # GET /countries/1/edit
  def edit
    @country = Country.find(params[:id])
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(params[:country])

    respond_to do |format|
      if @country.save
        format.html { redirect_to '/countries', notice: 'Country was successfully created.' }
        format.json { render json: @country, status: :created, location: @country }
      else
        format.html { render action: "new" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /countries/1
  # PUT /countries/1.json
  def update
    @country = Country.find(params[:id])

    respond_to do |format|
      if @country.update_attributes(params[:country])
        format.html { redirect_to '/countries', notice: 'Country was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country = Country.find(params[:id])
    @country.destroy

    respond_to do |format|
      format.html { redirect_to countries_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<div class="row">
  <!-- Example form styling -->
  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2><%= "Thêm" if @country == nil%> Quốc Gia</h2>
        <%if @country != nil %>
        <ul class="data-header-actions">
          <li>
            <a href="<%= countries_path %>" class="btn btn-success">Quốc Gia</a>
          </li>
        </ul>
        <% end %>
      </header>
      <section>
        <% @country = Country.new if @country == nil%>
        <%= form_for(@country,:html=>
        {:class=>"form-inline"}) do |f| %>
        <fieldset>
          <div class="control-group">
            <label class="control-label">Quận</label>
            <div class="form-controls">
              <div class="input-prepend">
                <%= f.text_field :name %></div>
            </div>
          </div>
          <div class="form-actions">
            <%= f.submit 'Save',:class=>'btn btn-alt btn-primary btn-large' %></div>
        </fieldset>
        <% end %></section>
    </div>
  </article>
  <!-- /Data block -->
</div>
<script type="text/javascript">
  <% if notice != nil %>
    alert('<%= notice%>');
  <% end %>
</script>

app/views/countries/edit.html.erb
<h1>Editing country</h1>

<%= render 'form' %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<!-- Grid row -->
<div class="row">
  <!-- Example jQuery FullCalendar -->
  <!-- Data block -->
  <article class="span6 data-block">
    <div class="data-container">
      <header>
        <h2>Quốc Gia</h2>
      </header>
      <section class="tab-content">
        <!-- Tab #static -->
        <div class="tab-pane active" id="static">
          <table class="table table-condensed">
            <thead>
              <tr>
                <th>Quốc Gia</th>
                <th></th>
              </tr>
            </thead>
            <tbody>
              <% @countries.each do |country| %>
              <tr>
                <td>
                  <span class="label btn-info">
                    <%= country.name %></span>
                </td>
                <td>
                  <%= link_to 'Show', country,:class=>
                  "label label-success" %>
                  <%= link_to 'Edit', edit_country_path(country),:class=>
                  "label label-success" %>
                  <%= link_to 'Destroy', country, method: :delete, data: { confirm: "Thực sự muốn xóa #{country.name} ?" },:class=>"label label-important" %></td>
              </tr>
              <% end %></tbody>
          </table>
        </div>
        <!-- /Tab #dynamic --> </section>
    </div>
  </article>
  <!-- /Data block -->
  <%= render :partial =>"countries/form"  %></div>
<!-- /Grid row -->

app/views/countries/new.html.erb
<%= render 'form' %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @country.name %>
</p>


<%= link_to 'Edit', edit_country_path(@country) %> |
<%= link_to 'Back', countries_path %>